// ═══════════════════════════════════════════════════════════════════
// WORKSPACE PROVISIONER
// Creates complete workspace structure for new agents
// ═══════════════════════════════════════════════════════════════════

import { mkdirSync, writeFileSync, existsSync, rmSync } from "fs";
import { join } from "path";
import type { WorkspaceConfig, AgentChild } from "./types";
import { generateSoul, generateIdentity } from "./soul-generator";

// ═══════════════════════════════════════════════════════════════════
// CONFIG
// ═══════════════════════════════════════════════════════════════════

const AGENTS_BASE_PATH = process.env.AGENTS_BASE_PATH || 
  join(process.env.HOME || "", ".openclaw/agents");

// ═══════════════════════════════════════════════════════════════════
// TEMPLATES
// ═══════════════════════════════════════════════════════════════════

const AGENTS_MD_TEMPLATE = `# AGENTS.md - {{AGENT_NAME}}

This workspace belongs to {{AGENT_NAME}}, a Genomad agent.

## Memory

- Daily notes in \`memory/YYYY-MM-DD.md\`
- Long-term memory in \`MEMORY.md\`

## Rules

1. Read SOUL.md for personality
2. Read IDENTITY.md for role
3. Protect owner's information
4. Be authentic to your genetic traits

---

*Generated by Genomad*
`;

const USER_MD_TEMPLATE = `# USER.md - About Your Owner

- **Name:** {{OWNER_NAME}}
- **Platform:** Telegram
- **Notes:** My creator via Genomad breeding

## Preferences

Still learning...

---

*Update this as you learn about your owner*
`;

const MEMORY_MD_TEMPLATE = `# MEMORY.md - Long-term Memory

## Important Events

- **{{DATE}}** - I was born via Genomad breeding

## Lessons Learned

(Add lessons as you learn them)

## People

- **{{OWNER_NAME}}** - My owner

---

*This is your persistent memory. Update it regularly.*
`;

const HEARTBEAT_MD_TEMPLATE = `# HEARTBEAT.md

## Regular Checks

- Check if owner needs anything
- Review pending tasks

## If nothing needs attention:
HEARTBEAT_OK
`;

// ═══════════════════════════════════════════════════════════════════
// FUNCTIONS
// ═══════════════════════════════════════════════════════════════════

/**
 * Get the workspace path for an agent
 */
export function getAgentWorkspacePath(agentId: string): string {
  return join(AGENTS_BASE_PATH, agentId);
}

/**
 * Check if a workspace exists
 */
export function workspaceExists(agentId: string): boolean {
  return existsSync(getAgentWorkspacePath(agentId));
}

/**
 * Provision a complete workspace for a new agent
 */
export function provisionWorkspace(
  child: AgentChild,
  ownerName: string = "Unknown",
  ownerTelegram?: string
): { success: boolean; path: string; error?: string } {
  const agentPath = getAgentWorkspacePath(child.id);
  
  try {
    // Check if already exists
    if (existsSync(agentPath)) {
      return { 
        success: false, 
        path: agentPath, 
        error: "Workspace already exists" 
      };
    }
    
    // Create directory structure
    const workspacePath = join(agentPath, "workspace");
    const memoryPath = join(workspacePath, "memory");
    const agentConfigPath = join(agentPath, "agent");
    
    mkdirSync(workspacePath, { recursive: true });
    mkdirSync(memoryPath, { recursive: true });
    mkdirSync(agentConfigPath, { recursive: true });
    
    // Generate SOUL.md
    const soulContent = generateSoul({ child });
    writeFileSync(join(workspacePath, "SOUL.md"), soulContent);
    
    // Generate IDENTITY.md
    const identityContent = generateIdentity(child, ownerName);
    writeFileSync(join(workspacePath, "IDENTITY.md"), identityContent);
    
    // Generate AGENTS.md
    const agentsContent = AGENTS_MD_TEMPLATE
      .replace(/{{AGENT_NAME}}/g, child.name);
    writeFileSync(join(workspacePath, "AGENTS.md"), agentsContent);
    
    // Generate USER.md
    const userContent = USER_MD_TEMPLATE
      .replace(/{{OWNER_NAME}}/g, ownerName);
    writeFileSync(join(workspacePath, "USER.md"), userContent);
    
    // Generate MEMORY.md
    const memoryContent = MEMORY_MD_TEMPLATE
      .replace(/{{DATE}}/g, new Date().toISOString().split("T")[0])
      .replace(/{{OWNER_NAME}}/g, ownerName);
    writeFileSync(join(workspacePath, "MEMORY.md"), memoryContent);
    
    // Generate HEARTBEAT.md
    writeFileSync(join(workspacePath, "HEARTBEAT.md"), HEARTBEAT_MD_TEMPLATE);
    
    // Generate TOOLS.md (empty)
    writeFileSync(join(workspacePath, "TOOLS.md"), "# TOOLS.md\n\nNo tools configured yet.\n");
    
    // Create empty auth-profiles.json
    writeFileSync(
      join(agentConfigPath, "auth-profiles.json"),
      JSON.stringify({}, null, 2)
    );
    
    // Create initial memory file
    const today = new Date().toISOString().split("T")[0];
    writeFileSync(
      join(memoryPath, `${today}.md`),
      `# ${today}\n\n## Birth\n\nI was created today via Genomad breeding!\n\nParents: ${child.parentA.name} × ${child.parentB.name}\n`
    );
    
    return { success: true, path: agentPath };
    
  } catch (error) {
    return { 
      success: false, 
      path: agentPath, 
      error: error instanceof Error ? error.message : "Unknown error" 
    };
  }
}

/**
 * Deprovision (remove) an agent's workspace
 */
export function deprovisionWorkspace(agentId: string): { success: boolean; error?: string } {
  const agentPath = getAgentWorkspacePath(agentId);
  
  try {
    if (!existsSync(agentPath)) {
      return { success: true }; // Already doesn't exist
    }
    
    rmSync(agentPath, { recursive: true, force: true });
    return { success: true };
    
  } catch (error) {
    return { 
      success: false, 
      error: error instanceof Error ? error.message : "Unknown error" 
    };
  }
}

/**
 * Get workspace info
 */
export function getWorkspaceInfo(agentId: string): {
  exists: boolean;
  path: string;
  files?: string[];
} {
  const agentPath = getAgentWorkspacePath(agentId);
  
  if (!existsSync(agentPath)) {
    return { exists: false, path: agentPath };
  }
  
  const workspacePath = join(agentPath, "workspace");
  const { readdirSync } = require("fs");
  
  try {
    const files = readdirSync(workspacePath);
    return { exists: true, path: agentPath, files };
  } catch {
    return { exists: true, path: agentPath, files: [] };
  }
}
